name: mondial_2026
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  audioplayers: ^6.7.1
  confetti: ^0.8.0
  url_launcher: ^6.3.2
  flutter_inappwebview: ^6.1.5
  uuid: ^4.5.3
  firebase_messaging: ^16.3.0
  google_fonts: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0
  benchmark_harness: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/initial_matches.json
    - assets/team_media.json
    - assets/logos/
    - assets/badges/
    - assets/mascots/
    - assets/avatars/
    - assets/team_profile_preview/
    - assets/app_icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  macos:
    generate: true
    image_path: "assets/launcher_icon_large.png"
  web:
    generate: true
    image_path: "assets/launcher_icon_large.png"
  image_path: "assets/launcher_icon_large.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/launcher_icon_padded.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/splash_icon_padded.png
  android_12:
    image: assets/splash_icon_padded.png
    color: "#000000"
