// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // FIX: Previously threw an UnsupportedError.
        // We can safely return the macOS config here since it contains your iOS App ID and Bundle ID.
        return macos;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_API_KEY',
    appId: '1:REDACTED_PROJECT_NUMBER:web:REDACTED_APP_ID',
    messagingSenderId: 'REDACTED_PROJECT_NUMBER',
    projectId: 'REDACTED_PROJECT_ID',
    authDomain: 'REDACTED_PROJECT_ID.firebaseapp.com',
    storageBucket: 'REDACTED_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_API_KEY',
    appId: '1:REDACTED_PROJECT_NUMBER:android:REDACTED_APP_ID',
    messagingSenderId: 'REDACTED_PROJECT_NUMBER',
    projectId: 'REDACTED_PROJECT_ID',
    storageBucket: 'REDACTED_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_API_KEY',
    appId: '1:REDACTED_PROJECT_NUMBER:ios:REDACTED_APP_ID',
    messagingSenderId: 'REDACTED_PROJECT_NUMBER',
    projectId: 'REDACTED_PROJECT_ID',
    storageBucket: 'REDACTED_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.mondial2026.mondial2026',
  );
}
