// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUFfMaITpS5UXAEsINYK-atbPLJsrjlE',
    appId: '1:1106243131:web:e750b217aa5c11120df61e',
    messagingSenderId: '1106243131',
    projectId: 'mondial-2026-challenge-8f',
    authDomain: 'mondial-2026-challenge-8f.firebaseapp.com',
    storageBucket: 'mondial-2026-challenge-8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6LAqpL3-dg7bDt5NX2_zW2RJ_qNvzoo',
    appId: '1:1106243131:android:50eddfb373cd45e10df61e',
    messagingSenderId: '1106243131',
    projectId: 'mondial-2026-challenge-8f',
    storageBucket: 'mondial-2026-challenge-8f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6G4MUq5qg-9L3YblixQ5D-T2XwhZkcvA',
    appId: '1:1106243131:ios:4e1979980f53f2c10df61e',
    messagingSenderId: '1106243131',
    projectId: 'mondial-2026-challenge-8f',
    storageBucket: 'mondial-2026-challenge-8f.firebasestorage.app',
    iosBundleId: 'com.mondial2026.mondial2026',
  );
}
